# Generated by Django 4.1.6 on 2023-02-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('es_maestra', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('spotify', 'Spotify'), ('Netflix', 'Netflix'), ('Star plus', 'Star plus')], max_length=200)),
                ('precio', models.IntegerField()),
                ('fecha_pago_recurrente', models.DateField()),
                ('capacidad', models.IntegerField()),
                ('cuenta_maestra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sellapp.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renovacion_mensual', models.IntegerField(verbose_name='Renovación mensual. Ej cada 1 mes, 2 meses, etc')),
                ('precio_mes', models.IntegerField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellapp.cuenta')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellapp.plan')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mes', models.IntegerField()),
                ('ciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellapp.cliente')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellapp.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='CobroPlanCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_pagado', models.DateField()),
                ('fue_pagado', models.BooleanField()),
                ('fecha_pago', models.DateField()),
                ('plan_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellapp.plancuenta')),
            ],
        ),
    ]
