# Generated by Django 4.1.5 on 2023-02-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
