# Generated by Django 4.1.5 on 2023-02-06 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0002_rename_apellido_cliente_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cuenta_maestra',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sellapp.cuenta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plancuenta',
            name='renovacion_mensual',
            field=models.IntegerField(verbose_name='Renovación mensual. Ej cada 1 mes, 2 meses, etc'),
        ),
    ]
