# Generated by Django 4.1.5 on 2023-02-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0003_plan_cuenta_maestra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tipo',
            field=models.CharField(choices=[('a', 'b')], default='a', max_length=200),
            preserve_default=False,
        ),
    ]
