# Generated by Django 4.1.5 on 2023-02-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0005_alter_plan_tipo_alter_plancuenta_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancuenta',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellapp.plan'),
        ),
    ]
