# Generated by Django 4.1.6 on 2023-02-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0007_alter_plancuenta_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='contrasena',
        ),
    ]
